In Zsh, interactively grep with <C-f>

diff --git a/.local/bin/fzf-state b/.local/bin/fzf-state
--- a/.local/bin/fzf-state
+++ b/.local/bin/fzf-state
@@ -8,6 +8,15 @@ case $1 in
         echo "alt-h:execute(fzf-state toggle hide-hidden-files)+reload($2),alt-i:execute(fzf-state toggle show-ignored-files)+reload($2)"
         exit
         ;;
+    context)
+        if [[ -z $2 ]]; then
+            echo "Error: expected a number!" >&2
+            exit 1
+        fi
+        start=$(( $2 - (FZF_PREVIEW_LINES / 2) ))
+        echo $(( start > 1 ? start : 0 ))
+        exit
+        ;;
     get-source)
         if [[ -f $FZF_STATE_PREFIX/hide-hidden-files ]]; then
             unset hidden
@@ -26,6 +35,9 @@ case $1 in
                 ;;
             directories)
                 eval fd $hidden $ignored --type=directory
+                ;;
+            grep)
+                eval rg --line-number --no-heading --color=always $hidden $ignored "\"$3\""
                 ;;
         esac
         exit
