chore(sh): modernise the shell scripts

diff --git a/.config/feh/find-lowres b/.config/feh/find-lowres
--- a/.config/feh/find-lowres
+++ b/.config/feh/find-lowres
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Recursively find images below a certain resolution
 #
@@ -9,22 +9,28 @@
 #
 # With -r: removes images instead of just listing them. Use at your own risk.
 
-remove=0
-
 while true; do
     case $1 in
-    -r) remove=(--action 'rm %F') ;;
+    -r | --remove)
+        action='--action=rm %F'
+        ;;
     - | --)
         shift
         break
         ;;
-    -*) echo "option \"$1\" ignored" ;;
-    *) break ;;
+    -*)
+        echo "Error: unknown option: $1" >&2
+        exit 1
+        ;;
+    *)
+        echo "Error: unknown argument: $1" >&2
+        exit 2
+        ;;
     esac
     shift
 done
 
-dir=${1:-.}
-dimension=${2:-1000x800}
+dir="${1:-.}"
+dimension="${2:-1000x800}"
 
-feh "${remove[@]}" -rlV --max-dim "${dimension}" "${dir}"
+feh --recursive --list --verbose --max-dim "$action" "$dimension" "$dir"
diff --git a/.local/bin/fzf-state b/.local/bin/fzf-state
--- a/.local/bin/fzf-state
+++ b/.local/bin/fzf-state
@@ -1,7 +1,7 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
 
 FZF_STATE_PREFIX=/tmp/fzf
-mkdir -p $FZF_STATE_PREFIX
+mkdir --parents $FZF_STATE_PREFIX
 
 case $1 in
 binds)
@@ -10,7 +10,7 @@ binds)
     ;;
 context)
     if [[ -z $2 ]]; then
-        echo "Error: expected a number!" >&2
+        echo "Error: expected a number" >&2
         exit 1
     fi
     start=$(($2 - (FZF_PREVIEW_LINES / 2)))
@@ -39,12 +39,16 @@ get-source)
     grep)
         eval rg --line-number --no-heading --color=always $hidden $ignored "\"$3\""
         ;;
+    *)
+        echo "Error: unknown argument: $2" >&2
+        exit 1
+        ;;
     esac
     exit
     ;;
 toggle)
     if [[ -z $2 ]]; then
-        echo "Error: no attribute given!" >&2
+        echo "Error: no attribute specified" >&2
         exit 1
     fi
 
@@ -57,5 +61,9 @@ toggle)
     fi
 
     exit
+    ;;
+*)
+    echo "Error: unknown argument: $1" >&2
+    exit 1
     ;;
 esac
diff --git a/.local/bin/mediactl b/.local/bin/mediactl
--- a/.local/bin/mediactl
+++ b/.local/bin/mediactl
@@ -1,63 +1,46 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
 
-#
-# Handles media playing and volume.
-#
-# The options are self explanatory.
-#
-# Author:	Benedikt Rips
-# Date:		2018/01/14
-#
-
-case "$1" in
-# Play
+case $1 in
 play)
     playerctl play
     ;;
-# Pause
 pause)
     playerctl pause
     ;;
-# Toggle between play and pause
 play-pause)
     playerctl play-pause
     ;;
-# Stop
 stop)
     playerctl stop
     ;;
-# Next track
 next)
     playerctl next
     ;;
-# Previous track
 previous)
     playerctl previous
     ;;
-# Raise the speakers volume
 speakers-raise)
     pactl set-sink-mute @DEFAULT_SINK@ 0
     pactl set-sink-volume @DEFAULT_SINK@ +5%
     ;;
-# Lower the speakers volume
 speakers-lower)
     pactl set-sink-mute @DEFAULT_SINK@ 0
     pactl set-sink-volume @DEFAULT_SINK@ -5%
     ;;
-# Toggle speakers mute
 speakers-mute)
     pactl set-sink-mute @DEFAULT_SINK@ toggle
     ;;
-# Raise the microphone's volume
 microphone-raise)
     pactl set-source-volume @DEFAULT_SOURCE@ +5%
     ;;
-# Lower the microphone's volume
 microphone-lower)
     pactl set-source-volume @DEFAULT_SOURCE@ -5%
     ;;
-# Toggle microphone mute
 microphone-mute)
     pactl set-source-mute @DEFAULT_SOURCE@ toogle
+    ;;
+*)
+    echo "Error: unknown argument: $1" >&2
+    exit 1
     ;;
 esac
diff --git a/.local/bin/screenshot b/.local/bin/screenshot
--- a/.local/bin/screenshot
+++ b/.local/bin/screenshot
@@ -1,11 +1,10 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
 
 # Takes a screenshot using scrot.  You can specify which area to take a
-# screenshot of. Possible options are:
-# 	focus, select, multidisp
-# By default, an screenshot of the entire screen is taken.
+# screenshot of. Possible options are: focus, select, multidisp.  By default, a
+# shot of the entire screen is taken.
 
-dir=$HOME/Pictures/Screenshots
+dir="$HOME/Pictures/Screenshots"
 
 for arg in "$@"; do
     case "$arg" in
@@ -15,18 +14,24 @@ for arg in "$@"; do
     -t | --temporary)
         dir=/tmp/screenshots
         ;;
+    -*)
+        echo "Error: unknown option: $arg" >&2
+        exit 1
+        ;;
     select)
         mode="--select"
         ;;
     window)
         mode="--window=$(xdotool getactivewindow)"
         ;;
-    *) ;;
-
+    *)
+        echo "Error: unknown argument: $arg" >&2
+        exit 2
+        ;;
     esac
 done
 
-mkdir -p "$dir"
+mkdir --parents "$dir"
 file="$dir/$(date +%Y%m%d-%H%M%S).png"
 
 maim "$mode" "$file" --hidecursor
diff --git a/.local/bin/switch_desktop b/.local/bin/switch_desktop
--- a/.local/bin/switch_desktop
+++ b/.local/bin/switch_desktop
@@ -1,29 +1,25 @@
-#!/usr/bin/bash
+#!/usr/bin/env bash
 
 # Handles diagonal desktop switching.  It takes the direction as an argument.
 # Whether and how the desktop is switched, depends then on the current desktop
 
-workspace=$(xdotool get_desktop)
+workspace="$(xdotool get_desktop)"
 
 case $1 in
 upleft)
-    if [[ $workspace == 0 ]]; then
-        xdotool set_desktop 3
-    fi
+    [[ $workspace == 0 ]] && xdotool set_desktop 3
     ;;
 upright)
-    if [[ $workspace == 1 ]]; then
-        xdotool set_desktop 2
-    fi
+    [[ $workspace == 1 ]] && xdotool set_desktop 2
     ;;
 downleft)
-    if [[ $workspace == 2 ]]; then
-        xdotool set_desktop 1
-    fi
+    [[ $workspace == 2 ]] && xdotool set_desktop 1
     ;;
 downright)
-    if [[ $workspace == 3 ]]; then
-        xdotool set_desktop 0
-    fi
+    [[ $workspace == 3 ]] && xdotool set_desktop 0
+    ;;
+*)
+    echo "Error: unknown direction: $1" >&2
+    exit 1
     ;;
 esac
